[tool.poetry]
name = "agentpkg"
version = "1.0.4"
description = "LangGraph Azure Function Agents"
authors = ["Example <example@example.com>"]
packages = [
    
    { include = "agentpkg" }
]

[tool.poetry.dependencies]
python = "^3.10"
azure-functions = "*"
pydantic = "*"
openai-agents = "*"
langchain = "*"
langgraph = "*"
langchain_community = "*"
langchain-core = "*"
openapi-schema-pydantic = "*"
requests = "*"
dacite = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
