name: Trunk-Based Release

# Trigger on commits to main *and* on any tag push
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  bump-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Determine bump level
        id: bump
        run: |
          # Are we running on a tag?  If so, bump major; otherwise bump minor
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "level=major" >> $GITHUB_OUTPUT
          else
            echo "level=minor" >> $GITHUB_OUTPUT
          fi

      - name: Bump version, commit & tag
        env:
          LEVEL: ${{ steps.bump.outputs.level }}
        run: |
          echo "Bumping version with: $LEVEL"
          poetry version "$LEVEL"
          NEW_VER=$(poetry version -s)
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pyproject.toml
          git commit -m "chore: bump version to v$NEW_VER"
          git tag "v$NEW_VER"
          git push origin HEAD --follow-tags

      - name: Build distribution
        run: |
          poetry build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/
          asset_name: |
            $(basename dist/*.tar.gz)
            $(basename dist/*.whl)
          asset_content_type: application/octet-stream
