name: Trunk-Based Release

on:
  # 1) Automatic patch bump on merges into main
  push:
    branches:
      - main

  # 2) Manual bump override
  workflow_dispatch:
    inputs:
      level:
        description: "Version bump level (patch, minor, major)"
        required: true
        default: "patch"

permissions:
  contents: write

jobs:
  bump-and-publish:
    runs-on: ubuntu-latest
    # → run on either a push to main (but not the Action’s own push)
    #    or a manual dispatch
    if: >-
      (
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        github.actor != 'github-actions'
      ) || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Determine bump level
        id: bump
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "level=${{ github.event.inputs.level }}" >> $GITHUB_OUTPUT
          else
            echo "level=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version, commit & tag
        env:
          LEVEL: ${{ steps.bump.outputs.level }}
        run: |
          echo "Bumping version with: $LEVEL"
          poetry version "$LEVEL"
          NEW_VER=$(poetry version -s)
          echo "new_version=v$NEW_VER" >> $GITHUB_OUTPUT
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pyproject.toml
          git commit -m "chore: bump to v$NEW_VER"
          git tag "v$NEW_VER"
          git push origin HEAD --follow-tags

      - name: Build distribution
        run: poetry build

      - name: Create Release & upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.bump.outputs.new_version }}
          artifacts: dist/*.tar.gz,dist/*.whl
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}



