name: Release Package

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Version bump level (patch, minor, major)"
        required: true
        default: "patch"
  push:
    tags:
      - 'v*.*.*'

jobs:
  bump-version:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install poetry
      - name: Bump version, commit & push tag
        env:
          LEVEL: ${{ github.event.inputs.level }}
        run: |
          poetry version "$LEVEL"
          NEW_VER=$(poetry version -s)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Bump version to v$NEW_VER"
          git tag "v$NEW_VER"
          git push origin HEAD --follow-tags

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install poetry

      - name: Build artifacts
        run: |
          poetry build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/
          asset_name: |
            $(basename dist/*.tar.gz)
            $(basename dist/*.whl)
          asset_content_type: application/octet-stream
